### ISSUE TITLE
Feature Request: Timed Metadata

### ISSUE THREAD

**Issue by PatrickMounteney** [m1ga/ti.exoplayer#1]
I wonder if it would be possible to expose the 'onMediaMetadataChanged' event to be able to retrieved timed metadata from a webstream?

Thanks,

Patrick Mounteney

patrick@kaleidoscopiccreation.co.uk

**Comment by m1ga** [comment]
I don't see any event in the library https://github.com/HamidrezaAmz/MagicalExoPlayer that connects to `onMediaMetadataChanged`. 
The native exoplayer module https://github.com/NetrisTV/ti.exoplayer has `metadata` event, so it might work with that one

**Comment by PatrickMounteney** [comment]
Thanks Michael,

That Russian one builds OK but won’t compile in Titanium due to being unable to find 'com.google.android.exoplayer:exoplayer:2.9.6.’ - it’s two years old so probably needs updating. 

And I have a feeling I did try that one out some time ago and found it didn’t play in the background (I know one I tried didn’t), whereas yours does.

Of course what I really want is an audio player to replace the ageing Woohoo audio player, with is long-in-the-tooth and has some issues. 


Best,

Patrick

**Comment by m1ga** [comment]
```
repositories {
	jcenter()
}
```
in your apps build.gradle to make it build. But I can't say anything about the functionality. But yes, the exoplayer is a bit older

About my module: you have to create an issue in the MagicalExoPlayer repo and ask for the event. If they implement it and update the version I can connect to that event.

**Comment by m1ga** [comment]
rewrote the module. You can now listen to the "metaData" event
