### ISSUE TITLE
Cross-protocol redirects

### ISSUE THREAD

**Issue by PatrickMounteney** [m1ga/ti.exoplayer#5]
By default Exoplayer doesn't allow cross-protocol redirects for stream URLs, but one can override that by adding allowCrossProtocolRedirects=true to the DefaultUriDataSource constructor.

Is this something that can be easily added as a property to the ti.exoplayer module?

Thanks.

**Comment by m1ga** [comment]
can you please try https://github.com/m1ga/ti.exoplayer/blob/main/android/dist/ti.exoplayer-android-3.1.2.zip with `crossProtocolRedirects:true` in your construction properties. I've added it from some demo code but not sure if it works :)

**Comment by PatrickMounteney** [comment]
Good evening Micheal,

Wow - you must be the fasted dev on the planet! Many thanks - I’ll try it tomorrow as I’ve just shut down my dev Mac for the evening (after along day).

Have a pleasant weekend.

Best,

Patrick

**Comment by PatrickMounteney** [comment]
Yes! crossProtocolRedirects: true works just fine Micheal - thanks once again.

**Comment by m1ga** [comment]
no problem :+1:
